apiVersion: apps/v1
#
# Create a deployment ( https://kubernetes.io/docs/concepts/workloads/controllers/deployment/ )
#
kind: Deployment
metadata:
  name: ingestor-deployment
spec:
  replicas: 1
  # The .spec.selector field defines how the Deployment finds which Pods to manage.
  # In this case, you simply select a label that is defined in the Pod template (app: blog).
  # However, more sophisticated selection rules are possible,
  # as long as the Pod template itself satisfies the rule.
  selector:
    matchLabels:
      app: ingestor
  template:
    metadata:
      labels:
        app: ingestor
    spec:
      containers:
      - name: ingestor
        image: "gcr.io/custom-tine-287322/thingsIO/ingestor:1.0"
        ports:
        - containerPort: 5000
        env:
          - name: FLASK_PORT
            value: "5000"

